version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    user: root
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrongPassw0rd!
    volumes:
      - mssql-data:/var/opt/mssql/data
    ports:
      - 1433:1433

volumes:
  mssql-data: